### ISSUE TITLE
raise CalledProcessError when trying to start benchmark

### ISSUE THREAD

**Issue by snazhmudinov** [bazelbuild/bazel-bench#146]
Hi

I have followed the installation instructions, and tried to do some test benchmarking. But it fails with the following error:
https://gist.github.com/snazhmudinov/fe4b9140135eb3d9c1b42bb9b808a51d

Command I'm trying to run:
```
bazel run :benchmark \
-- \
--project_source=https://github.com/bazelbuild/rules_cc.git \
--data_directory=/tmp/bazel-bench-data \
--verbose \
-- build //:all
```

I have bazelisk, python/python3, git installed. I have also installed all the 3rd party requirements (according to installation guides).

I'm on macbook air: 1.6 GHz Dual-Core Intel Core i5, MacOS 12.6,

**Comment by tjgq** [comment]
I can't reproduce this on my machine, sorry.

The crash occurs while `bazel-bench` is building Bazel at head. Can you confirm that you're able to successfully build it on your machine? (`git clone http:s//github.com/bazelbuild/bazel && cd bazel && bazel build //src:bazel`)

(Alternatively, if you'd rather use a pre-built Bazel version to benchmark, you can pass in the `--bazel_binaries` flag.)

**Comment by snazhmudinov** [comment]
I had no issue building //src:bazel.
```
INFO: Elapsed time: 2068.275s, Critical Path: 246.83s
INFO: 3541 processes: 294 internal, 2466 darwin-sandbox, 1 local, 780 worker.
INFO: Build completed successfully, 3541 total actions
```

**Comment by joeleba** [comment]
Can you please run the benchmark again with `--verbose`?
