### ISSUE TITLE
Build fails with Python toolchains flag flip

### ISSUE THREAD

**Issue by brandjon** [bazelbuild/bazel-bench#29]
Bazel 0.27 turns on [`--incompatible_use_python_toolchains`](https://github.com/bazelbuild/bazel/issues/7899). According to a recent [downstream CI run with the flag flip](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1008#ea36e43e-a356-4204-8233-49bd47d936a7), this project [fails](https://storage.googleapis.com/bazel-untrusted-buildkite-artifacts/ea36e43e-a356-4204-8233-49bd47d936a7/utils/bazel_test/attempt_1.log), probably because the flag flip causes it to use the *correct* Python version (as requested by the target) instead of whatever the system `python` version is. You can likely fix this by adding `python_version = "PY2"` to your Python 2 targets.

**Comment by laszlocsomor** [comment]
@joeleba ping
