### ISSUE TITLE
Display non-zero exit status in summary

### ISSUE THREAD

**Issue by meisterT** [bazelbuild/bazel-bench#39]
**Description of the problem / feature request:**

It's easy to miss a non-zero exit status in the long build log. It should also be visible in the results summary in the end.

If not all runs have the same status, you may even consider excluding measurements from non-zero exit code runs.

**Feature requests: what underlying problem are you trying to solve with this feature?**

Make it easy to detect errors / flakiness.

**Comment by joeleba** [comment]
This is related to https://github.com/bazelbuild/bazel-bench/issues/31. To allow both approaches (stepping the script immediately vs just reporting failures), we can introduce a flag `--carry_on`.
