### ISSUE TITLE
[BazelCI] Add option to benchmark every X commit

### ISSUE THREAD

**Issue by joeleba** [bazelbuild/bazel-bench#57]
**Description of the problem / feature request:**

As there's a timeout limit, it's not practical to run benchmarking at every commit (also we need to maintain the number of runs per commit to achieve statistical significance). We need an option to benchmark every X commit in the commit list.

**Comment by meisterT** [comment]
I think it should be the other way around: benchmark X commits (evenly spaced) out of the list of N commits.

**Comment by joeleba** [comment]
Yes, that idea did cross my mind too right after I created this issue. SGTM.

**Comment by joeleba** [comment]
Closed with [continuous-integration#751](https://github.com/bazelbuild/continuous-integration/pull/751).
